# taps
tap "homebrew/cask-fonts"

# command line utilities
brew "bat"
brew "dog"
brew "duf"
brew "dust"
brew "exa"
brew "fd"
brew "fnm"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gron"
brew "htop"
brew "imageoptim-cli"
brew "jo"
brew "jq"
brew "noahgorstein/tap/jqp"
brew "jotaen/klog/klog"
brew "mas"
brew "mycli"
brew "prettyping"
brew "pnpm"
brew "procs"
brew "python"
brew "harelba/q/q"
brew "rename"
brew "ripgrep"
brew "shellcheck"
brew "sd"
brew "trash"
brew "tree"
brew "vim"
brew "vhs"
brew "wget"
brew "zsh"
brew "zoxide"
brew "xh"

# completions
brew "bash-completion"
brew "docker-completion"

# casks
cask "appcleaner"
cask "bartender"
cask "dash"
cask "docker"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "flux"
cask "fork"
cask "google-chrome"
cask "imageoptim"
cask "karabiner-elements"
cask "slack" 
cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"
cask "warp"
cask "1password"
cask "1password/tap/1password-cli"

# Mac App Store applications
mas "Battery Indicator", id: 1206020918
mas "Bear", id: 1091189122
mas "Dato", id: 1470584107
mas "Magnet", id: 441258766
mas "Spark", id: 1176895641

# Quick Look plugins
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
cask "qlimagesize"
cask "suspicious-package"
cask "qlvideo"

# fonts
cask "font-jetbrains-mono"
