#!/usr/bin/env bash

shell="$(dscl . -read ~/ UserShell | rev | cut -d' ' -f1 | rev)"

if ! [ "$shell" = "$(brew --prefix)/bin/zsh" ]; then
  zsh_path="$(which zsh)"
  echo "$zsh_path" | sudo tee -a /etc/shells
  sudo dscl . -create "$HOME" UserShell "$zsh_path"
  chsh -s "$zsh_path"
fi
