#!/usr/bin/env bash

shell=$(dscl . -read ~/ UserShell)

if ! [ "$shell" = "$(brew --prefix)/bin/zsh" ]; then
  zsh_path="$(which zsh)"
  echo "$zsh_path" | sudo tee -a /etc/shells
  sudo dscl . -create /Users/$USER UserShell "$zsh_path"
  chsh -s "$zsh_path"
fi
