#!/usr/bin/env bash

./change_shell
./fix_permissions
./brew_updater/install
curl -o- -L https://yarnpkg.com/install.sh | bash
./install_global_npm_packages
pip3 install -r requirements.txt
"$(brew --prefix)"/opt/fzf/install
